# Robustness and Plasticity in Regulatory Networks

* [Introduction](./RPRN-Introduction.ipynb)
* [BoolNet](./RPRN-BoolNet.ipynb)
* [Functions](./RPRN-Functions.ipynb)
* [Updating](#Updating)
    * [Synchronous vs asynchronous](#Synchronous-vs-asynchronous)
    * [Transition table](#Transition-table)
* [States and trajectories](./RPRN-States-Trajectories.ipynb)
* [Appendix](./RPRN-Appendix.ipynb)

# Updating

## Synchronous vs asynchronous

In a discrete regulatory network the value of a node $n$ in $t+1$ is a function of the values of its regulators in the time $t. However, we can [update the value of the nodes in different ways](http://www.biorxiv.org/content/biorxiv/early/2014/10/19/010504.full.pdf). The two most common are synchronous -where all nodes are updated at the same time- and asynchronous -where the nodes are updated one by one.

If synchronous updates are used each state the transition space has only one successor. However, if asynchronous updates are used each state the transition space can have more than one successor. Complex attractors depend on the updating policy and are harder and more expensive to compute in the asynchronous case. 

Biologicaly speaking, synchronous updates supose that all the processes happen at exactly the same time, while asynchronous updates supose that the processes do not.

We can obtain the attrators using synchronous and the asynchronous updates with BoolNet. First, lets call BoolNet and create a network using the Th17/iTreg model.

In [1]:
#Uncomment next line if you haven't installed BoolNet
#install.packages("BoolNet", repos='http://cran.us.r-project.org')
library(BoolNet)

In [2]:
net <- loadNetwork("minTh17iTreg.txt")
net

Boolean network with 10 genes

Involved genes:
IL2 RORGT STAT3 FOXP3 TGFB IL10 IL2e IL21e TGFBe IL10e

Transition functions:
IL2 = (IL2e | (IL2 &  ! FOXP3)) &  ! (STAT3 | (IL10 & ! FOXP3))
RORGT = (STAT3 & TGFB) &  ! FOXP3
STAT3 = (IL21e | STAT3 | RORGT) &  ! (IL10 | IL2)
FOXP3 = (IL2 & (TGFB | FOXP3)) &  ! (STAT3 | RORGT)
TGFB = TGFBe | ((TGFB | FOXP3) &  ! STAT3 )
IL10 = IL10e | (IL10 & (STAT3 | TGFB))
IL2e = IL2e
IL21e = IL21e
TGFBe = TGFBe
IL10e = IL10e

Then, lets compute the synchronous and asynchronous attractors and see the number of attractors each method found.

In [5]:
attr.sync <- getAttractors(net)
attr.async <- getAttractors(net, type="asynchronous")
length(attr.sync$attractors)
length(attr.async$attractors)

[1] 58

[1] 31

As you can see, the asynchronous method returns less attractors. Lets compare the two attractors lists. In the first place it is neccesary to obtain a list of the states involved in each attractor set.

In [6]:
attr.sync.states <- sapply( attr.sync$attractors, function (a) {a$involvedStates})
attr.sync.states
attr.async.states <- sapply( attr.async$attractors, function (a) {a$involvedStates})
attr.async.states

[[1]]
     [,1]
[1,]    0

[[2]]
     [,1]
[1,]    1

[[3]]
     [,1]
[1,]    4

[[4]]
     [,1]
[1,]   16

[[5]]
     [,1]
[1,]   48

[[6]]
     [,1]
[1,]   65

[[7]]
     [,1]
[1,]   68

[[8]]
     [,1]
[1,]   89

[[9]]
     [,1]
[1,]  112

[[10]]
     [,1]
[1,]  121

[[11]]
     [,1]
[1,]  132

[[12]]
     [,1]
[1,]  129

[[13]]
     [,1]
[1,]  176

[[14]]
     [,1]
[1,]  193

[[15]]
     [,1]
[1,]  196

[[16]]
     [,1]
[1,]  217

[[17]]
     [,1]
[1,]  240

[[18]]
     [,1]
[1,]  249

[[19]]
     [,1]
[1,]  272

[[20]]
     [,1]
[1,]  278

[[21]]
     [,1]
[1,]  304

[[22]]
     [,1]
[1,]  345

[[23]]
     [,1]
[1,]  342

[[24]]
     [,1]
[1,]  368

[[25]]
     [,1]
[1,]  377

[[26]]
     [,1]
[1,]  406

[[27]]
     [,1]
[1,]  432

[[28]]
     [,1]
[1,]  473

[[29]]
     [,1]
[1,]  470

[[30]]
     [,1]
[1,]  496

[[31]]
     [,1]
[1,]  505

[[32]]
     [,1]
[1,]  544

[[33]]
     [,1]
[1,]  560

[[34]]
     [,1]
[1,]  608

[[35]]
     [,1]
[1,]  633

[[36]]
     [,1]
[1,]  624

[[37]]
     [,1]
[1,]  672

[[38]]
     [,1]
[1,]  688

[[39]]
     [,1]
[1,]  736

[[40]]
     [,1]
[1,]  761

[[41]]
     [,1]
[1,]  752

[[42]]
     [,1]
[1,]  816

[[43]]
     [,1]
[1,]  880

[[44]]
     [,1]
[1,]  889

[[45]]
     [,1]
[1,]  944

[[46]]
     [,1]
[1,] 1008

[[47]]
     [,1]
[1,] 1017

[[48]]
     [,1] [,2]
[1,]  113  120

[[49]]
     [,1] [,2]
[1,]  192  197

[[50]]
     [,1] [,2]
[1,]  241  248

[[51]]
     [,1] [,2]
[1,]  338  341

[[52]]
     [,1] [,2]
[1,]  369  376

[[53]]
     [,1] [,2]
[1,]  466  469

[[54]]
     [,1] [,2]
[1,]  497  504

[[55]]
     [,1] [,2]
[1,]  625  632

[[56]]
     [,1] [,2]
[1,]  753  760

[[57]]
     [,1] [,2]
[1,]  881  888

[[58]]
     [,1] [,2]
[1,] 1009 1016

[1]  304   89    1  470   65  278  624  496  432  672  560   48  176  816 1008
[16]    4  944  129   68 1017  736  406  880  272   16  217  342  121  345  132
[31]  688

Lets determine  how many states are present in both, how many only in the synchronous attractors, and how many only in the synchronous attractors.

In [7]:
length(intersect(attr.sync.states,attr.async.states))
length(setdiff(attr.sync.states,attr.async.states))
length(setdiff(attr.async.states,attr.sync.states))

[1] 31

[1] 27

[1] 0

As you can see, all the asynchronous attractors are also in the synchronous attractors, but the reverse is not true. In particular, most cycles tend to dissapear in the asynchronous case.

Lets see the attractors in the intersecion.

In [8]:
intersect(attr.sync.states,attr.async.states)

[1]    1    4   16   48   65   68   89  121  132  129  176  217  272  278  304
[16]  345  342  406  432  470  496  560  624  672  688  736  816  880  944 1008
[31] 1017

Lets see the attractors that belong only to the synchronous case, this are the attractors we lost in the asynchronous update.

In [9]:
setdiff(attr.sync.states,attr.async.states)

[[1]]
     [,1]
[1,]    0

[[2]]
     [,1]
[1,]  112

[[3]]
     [,1]
[1,]  193

[[4]]
     [,1]
[1,]  196

[[5]]
     [,1]
[1,]  240

[[6]]
     [,1]
[1,]  249

[[7]]
     [,1]
[1,]  368

[[8]]
     [,1]
[1,]  377

[[9]]
     [,1]
[1,]  473

[[10]]
     [,1]
[1,]  505

[[11]]
     [,1]
[1,]  544

[[12]]
     [,1]
[1,]  608

[[13]]
     [,1]
[1,]  633

[[14]]
     [,1]
[1,]  761

[[15]]
     [,1]
[1,]  752

[[16]]
     [,1]
[1,]  889

[[17]]
     [,1] [,2]
[1,]  113  120

[[18]]
     [,1] [,2]
[1,]  192  197

[[19]]
     [,1] [,2]
[1,]  241  248

[[20]]
     [,1] [,2]
[1,]  338  341

[[21]]
     [,1] [,2]
[1,]  369  376

[[22]]
     [,1] [,2]
[1,]  466  469

[[23]]
     [,1] [,2]
[1,]  497  504

[[24]]
     [,1] [,2]
[1,]  625  632

[[25]]
     [,1] [,2]
[1,]  753  760

[[26]]
     [,1] [,2]
[1,]  881  888

[[27]]
     [,1] [,2]
[1,] 1009 1016

As we can see, cycles -and some of the steady state- where not robust to the update schema.

However, using asynchronous updates complicates determining the size of the basin of attraction. In asynchronous updating is used a initial state can reach two different attractors depending of the trajectory,  which makes it possible to determine the basin of attraction. (It is possible to estimate the asynchronous basin of attraction with random walks.)

In [12]:
attr.sync$attractors[[1]]
attr.async$attractors[[1]]

$involvedStates
     [,1]
[1,]    0

$basinSize
[1] 27


$involvedStates
     [,1]
[1,]  304

$basinSize
[1] NA


Synchronous updates are deterministic, this means each state has only one sucessor. However, in asynchoronous updates, states can have more than one sucessor, which makes it hard to determine the basin size. This can complicate the analysis of the system and add computational time. It is for this reason that synchronous updating is usually used.

Asynchronous updates usually result in less attractors, however, all the attractors present in the asynchronous update will be present in the synchronous. It is important to check the asynchronous attractors as complex attractors -specially cyclic attractors- are not robust to the update method and may not occur in biological systems that are asynchronous.

## Transition table

The dynamics of a regulatory network can be expressed as a transition table, where each state is followed by an other. Perturbing the transitions between states can show the robustness to noise in the dynamic trajectory in the system.

We can do simulate this perturbations in the transitions using the BoolNet function __perturbNetwork()__.

In [15]:
perturbed.net <- perturbNetwork(net, perturb="transitions", numStates=10)
perturbed.attr <- getAttractors(perturbed.net)
perturbed.states <- sapply(perturbed.attr$attractors, "[[", 1)           
perturbed.states

[[1]]
     [,1]
[1,]    0

[[2]]
     [,1]
[1,]    1

[[3]]
     [,1]
[1,]    4

[[4]]
     [,1]
[1,]   16

[[5]]
     [,1]
[1,]   48

[[6]]
     [,1]
[1,]   65

[[7]]
     [,1]
[1,]   68

[[8]]
     [,1]
[1,]   89

[[9]]
     [,1]
[1,]  112

[[10]]
     [,1]
[1,]  121

[[11]]
     [,1]
[1,]  132

[[12]]
     [,1]
[1,]  129

[[13]]
     [,1]
[1,]  176

[[14]]
     [,1]
[1,]  193

[[15]]
     [,1]
[1,]  196

[[16]]
     [,1]
[1,]  217

[[17]]
     [,1]
[1,]  240

[[18]]
     [,1]
[1,]  249

[[19]]
     [,1]
[1,]  272

[[20]]
     [,1]
[1,]  278

[[21]]
     [,1]
[1,]  304

[[22]]
     [,1]
[1,]  345

[[23]]
     [,1]
[1,]  342

[[24]]
     [,1]
[1,]  368

[[25]]
     [,1]
[1,]  377

[[26]]
     [,1]
[1,]  406

[[27]]
     [,1]
[1,]  432

[[28]]
     [,1]
[1,]  496

[[29]]
     [,1]
[1,]  470

[[30]]
     [,1]
[1,]  505

[[31]]
     [,1]
[1,]  544

[[32]]
     [,1]
[1,]  560

[[33]]
     [,1]
[1,]  608

[[34]]
     [,1]
[1,]  633

[[35]]
     [,1]
[1,]  624

[[36]]
     [,1]
[1,]  672

[[37]]
     [,1]
[1,]  688

[[38]]
     [,1]
[1,]  736

[[39]]
     [,1]
[1,]  761

[[40]]
     [,1]
[1,]  752

[[41]]
     [,1]
[1,]  816

[[42]]
     [,1]
[1,]  880

[[43]]
     [,1]
[1,]  889

[[44]]
     [,1]
[1,]  944

[[45]]
     [,1]
[1,] 1008

[[46]]
     [,1]
[1,] 1017

[[47]]
     [,1] [,2]
[1,]  113  120

[[48]]
     [,1] [,2]
[1,]  192  197

[[49]]
     [,1] [,2]
[1,]  241  248

[[50]]
     [,1] [,2]
[1,]  338  341

[[51]]
     [,1] [,2]
[1,]  369  376

[[52]]
     [,1] [,2]
[1,]  466  469

[[53]]
     [,1] [,2]
[1,]  497  504

[[54]]
     [,1] [,2]
[1,]  625  632

[[55]]
     [,1] [,2]
[1,]  753  760

[[56]]
     [,1] [,2]
[1,]  881  888

[[57]]
     [,1] [,2]
[1,] 1009 1016

We can compare this results with the attractors of our WT network. Here we show the difference between the two sets of attractors. 

In [16]:
setdiff(attr.sync.states, perturbed.states)

[[1]]
     [,1]
[1,]  473

As __perturbNetwork()__ randomly changes the transition table it is a good idea to repeat the experiment multiple times.

# Index

* [Introduction](./RPRN-Introduction.ipynb)
* [BoolNet](./RPRN-BoolNet.ipynb)
* [Functions](./RPRN-Functions.ipynb)
* Updating
* [States and trajectories](./RPRN-States-Trajectories.ipynb)
* [Appendix](./RPRN-Appendix.ipynb)